# Array

In [3]:
# create An array
import numpy as np

In [5]:
arr=np.array([1,2,3,4])
print (arr)

[1 2 3 4]


In [6]:
# 0-Dim array
arr=np.array(23)
print(arr)

23


In [7]:
# 1-D array
arr+np.array([1,2,3,4])
print(arr)

23


In [9]:
# 2-D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
# 3-D array
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [12]:
arr.ndim

3

In [13]:
#Multi-dimensional array
arr=np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [14]:
#Accessing an array
my_array=np.array([1,2,3,4])
print(my_array)

[1 2 3 4]


In [17]:
#Upcasting data types
my_array=np.array([1,2,3,'4'])
print(my_array)

['1' '2' '3' '4']


In [18]:
my_array=np.array([1,2,3,4.5])
print(my_array)

[1.  2.  3.  4.5]


In [19]:
my_array=np.array([1,2,3,4])
print(my_array[0])

1


In [21]:
my_array=np.array([1,2,3,4])
print(my_array[0:2])

[1 2]


In [26]:
#Using index on a 2-D array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array[1,0:2])

[5 6]


In [ ]:
#Array VS Lists

In [27]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1+my_list2}')

LIST:[1, 2, 3, 4, 5, 6, 7, 8]


In [29]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1+my_array2}')

ARRAY:[ 6  8 10 12]


In [35]:
# Adding a single element
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
print(f'LIST:{my_list1[1]+my_list2[1]}')

LIST:8


In [36]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1[1]+my_array2[1]}')

ARRAY:8


In [43]:
my_array1=np.array([1,2,3,4])
my_array2=np.array([5,6,7,8])
print(f'ARRAY:{my_array1**my_array2}')

ARRAY:[    1    64  2187 65536]


In [48]:
# copy of an array using .copy()
my_array=np.array([1,2,3,4])
array_copy=my_array.copy()
my_array[1]=55
print(f'original Array:{my_array}')
print(f'Copied Array:{array_copy}')

original Array:[ 1 55  3  4]
Copied Array:[1 2 3 4]


In [49]:
# View in an array
# Copy an array using .copy()
my_array=np.array([1,2,3,4])
viewed_copy=my_array.view()
my_array[1]=55
print(f'original Array:{my_array}')
print(f'viewed Array:{viewed_copy}')

original Array:[ 1 55  3  4]
viewed Array:[ 1 55  3  4]


In [45]:
# Iterating an array
my_array=np.array([1,2,3,4])
for x in my array:
    print(x)

SyntaxError: invalid syntax (1909586235.py, line 3)

In [47]:
# joining 2 arrays
my_array1=np.array([[1,2,3,4],[5,6,7,8]])
my_array2=np.array([[9,10,11,12],[13,14,15,16]])
print(np.concatenate((my_array1,my_array2),axis=1))

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [ ]:
# Joining using stack


In [50]:
# Splitting an array
my_array=np.array([1,2,3,4])
print(np.array_split(my_array,2))

[array([1, 2]), array([3, 4])]


In [51]:
# Searching for a value in an array using where() returns an index position
my_array=np.array([1,2,3,4])
print(np.where(my_array==3))

(array([2], dtype=int64),)


In [52]:
# Sorting the array using the sort()
my_array=np.array([10,20,39,45,65,69])
print(np.sort(my_array))

[10 20 39 45 65 69]


In [53]:
# sorting in descending order
my_array=np.array([10,20,39,45,65,69])
print(np.sort(my_array)[::-1])

[69 65 45 39 20 10]


In [60]:
# filtering an array
my_array=np.array([10,20,39,45,65,69])
filtered_array=my_array>30

In [61]:
filtered_array

array([False, False,  True,  True,  True,  True])

In [62]:
print(my_array[filtered_array])

[39 45 65 69]


In [63]:
# create an array of 5x5 (Generates random numbers)
np.random.rand(5,5)

array([[0.05731252, 0.82308955, 0.71887757, 0.81427191, 0.15695701],
       [0.60141349, 0.85144998, 0.53941569, 0.69341499, 0.31791902],
       [0.63647039, 0.6038021 , 0.66229086, 0.94673612, 0.81635232],
       [0.11570056, 0.21681951, 0.54933921, 0.05494618, 0.19322582],
       [0.49316772, 0.42762102, 0.09763781, 0.92306272, 0.17429253]])

In [64]:
print(my_array.shape)

(6,)


In [65]:
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array.shape)

(2, 4)


In [66]:
# Reshaping an array
my_array=np.array([1,2,3,4])
print(my_array.reshape(2,2))

[[1 2]
 [3 4]]


In [67]:
# Reshaping a multidim into a single array
my_array=np.array([[1,2,3,4],[5,6,7,8]])
print(my_array.reshape(1,8))

[[1 2 3 4 5 6 7 8]]
